# Generated by Django 3.1.3 on 2020-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20201114_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='old author', max_length=255),
            preserve_default=False,
        ),
    ]
