# Generated by Django 3.1.3 on 2020-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ManyToManyField(related_name='comment', to='wall_app.users'),
        ),
    ]
