# Generated by Django 3.1.3 on 2020-11-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old dojo', max_length=255),
            preserve_default=False,
        ),
    ]
