# Generated by Django 3.1.3 on 2020-11-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('br_app', '0002_auto_20201119_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='br_app.books'),
        ),
    ]
